# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - parameter_assignments
    - prefer_const_declarations
    - prefer_final_locals

analyzer:
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
#   exclude:
#     - path/to/excluded/files/**
